// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/match_helper.proto

package match_helper

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for MatchHelper service

func NewMatchHelperEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for MatchHelper service

type MatchHelperService interface {
	FillData(ctx context.Context, in *FillDataReq, opts ...client.CallOption) (*FillDataRsp, error)
}

type matchHelperService struct {
	c    client.Client
	name string
}

func NewMatchHelperService(name string, c client.Client) MatchHelperService {
	return &matchHelperService{
		c:    c,
		name: name,
	}
}

func (c *matchHelperService) FillData(ctx context.Context, in *FillDataReq, opts ...client.CallOption) (*FillDataRsp, error) {
	req := c.c.NewRequest(c.name, "MatchHelper.FillData", in)
	out := new(FillDataRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MatchHelper service

type MatchHelperHandler interface {
	FillData(context.Context, *FillDataReq, *FillDataRsp) error
}

func RegisterMatchHelperHandler(s server.Server, hdlr MatchHelperHandler, opts ...server.HandlerOption) error {
	type matchHelper interface {
		FillData(ctx context.Context, in *FillDataReq, out *FillDataRsp) error
	}
	type MatchHelper struct {
		matchHelper
	}
	h := &matchHelperHandler{hdlr}
	return s.Handle(s.NewHandler(&MatchHelper{h}, opts...))
}

type matchHelperHandler struct {
	MatchHelperHandler
}

func (h *matchHelperHandler) FillData(ctx context.Context, in *FillDataReq, out *FillDataRsp) error {
	return h.MatchHelperHandler.FillData(ctx, in, out)
}
