// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.2
// source: proto/match_helper.proto

package match_helper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FillDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Tt    int64 `protobuf:"varint,2,opt,name=tt,proto3" json:"tt,omitempty"`
}

func (x *FillDataReq) Reset() {
	*x = FillDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_match_helper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FillDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillDataReq) ProtoMessage() {}

func (x *FillDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_helper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillDataReq.ProtoReflect.Descriptor instead.
func (*FillDataReq) Descriptor() ([]byte, []int) {
	return file_proto_match_helper_proto_rawDescGZIP(), []int{0}
}

func (x *FillDataReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *FillDataReq) GetTt() int64 {
	if x != nil {
		return x.Tt
	}
	return 0
}

type FillDataRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *FillDataRsp) Reset() {
	*x = FillDataRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_match_helper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FillDataRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillDataRsp) ProtoMessage() {}

func (x *FillDataRsp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_match_helper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillDataRsp.ProtoReflect.Descriptor instead.
func (*FillDataRsp) Descriptor() ([]byte, []int) {
	return file_proto_match_helper_proto_rawDescGZIP(), []int{1}
}

func (x *FillDataRsp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_match_helper_proto protoreflect.FileDescriptor

var file_proto_match_helper_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x68, 0x65,
	0x6c, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x5f, 0x68, 0x65, 0x6c, 0x70, 0x65, 0x72, 0x22, 0x33, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x6c,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x74, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x74, 0x22, 0x21, 0x0a,
	0x0b, 0x46, 0x69, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x32, 0x52, 0x0a, 0x0c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x68, 0x65, 0x6c, 0x70, 0x65, 0x72,
	0x12, 0x42, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x2e, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x5f, 0x68, 0x65, 0x6c, 0x70, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6c, 0x6c,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f,
	0x68, 0x65, 0x6c, 0x70, 0x65, 0x72, 0x2e, 0x46, 0x69, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x73, 0x70, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x68, 0x65, 0x6c, 0x70, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_match_helper_proto_rawDescOnce sync.Once
	file_proto_match_helper_proto_rawDescData = file_proto_match_helper_proto_rawDesc
)

func file_proto_match_helper_proto_rawDescGZIP() []byte {
	file_proto_match_helper_proto_rawDescOnce.Do(func() {
		file_proto_match_helper_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_match_helper_proto_rawDescData)
	})
	return file_proto_match_helper_proto_rawDescData
}

var file_proto_match_helper_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_match_helper_proto_goTypes = []interface{}{
	(*FillDataReq)(nil), // 0: match_helper.FillDataReq
	(*FillDataRsp)(nil), // 1: match_helper.FillDataRsp
}
var file_proto_match_helper_proto_depIdxs = []int32{
	0, // 0: match_helper.Match_helper.FillData:input_type -> match_helper.FillDataReq
	1, // 1: match_helper.Match_helper.FillData:output_type -> match_helper.FillDataRsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_match_helper_proto_init() }
func file_proto_match_helper_proto_init() {
	if File_proto_match_helper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_match_helper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FillDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_match_helper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FillDataRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_match_helper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_match_helper_proto_goTypes,
		DependencyIndexes: file_proto_match_helper_proto_depIdxs,
		MessageInfos:      file_proto_match_helper_proto_msgTypes,
	}.Build()
	File_proto_match_helper_proto = out.File
	file_proto_match_helper_proto_rawDesc = nil
	file_proto_match_helper_proto_goTypes = nil
	file_proto_match_helper_proto_depIdxs = nil
}
